### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by raytrax** [hybridus/heartbleedscanner#1]
Hi,
Thanks for ur work and time.
You could add in the documentation how to interpret the log output?
Two dots, dot and "F", etc.

Example log:
1.2.3.4  ..
1.2.3.4 .F
1.2.3.4  .F

Thanks

**Comment by hybridus** [comment]
Hi,

I'll commit a new version with a fixed log output feature.

For now you may use:  

gawk -F '++a[$1] > 4' | gawk -F' ' '{ print $1 }' logfile.txt

I didn't tested its accuracy but it should work fine. Parses the file with space character and selects the first field(IP Address) and checks for the repeating line more than 4.

Hope it helps for you

**Comment by raytrax** [comment]
Thank you very much, in the end I uses this command: 
cat logfile.txt | awk '{ print $1} ' | uniq -c | grep -v " 4|3 |2 | 1 " | awk '{ print $2} '> huntedip.txt
